version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "helloworld2022"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1scd1r0lsbgom"
s3_prefix = "helloworld2022"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=866030846001.dkr.ecr.us-west-2.amazonaws.com/helloworld2022fbf1a607/helloworldfunction19d43fc4repo"]
